[Pantalla] Login
w-etc/geoStories pull request #11
Opened 2020-11-03 00:14 UTC by ItuFede

Creación de Login:

- Formulario de Login.
- Lógica del Login.

Se agrega Pantalla:

-Bienvenida (Botón para entrar de manera anónima)
-Iniciar sesión
-Registrarse (Sin comportamiento)

Dentro de la pantalla de registro están los botones de Oauth (Implementación comentada)

2020-11-03 21:07 UTC, w-etc requested changes
Dejo cosas para corregir abajo, otras son preguntas

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Login/components/body.dart
> +}
Este componente no se usa en ningún lado

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Login/login_screen.dart
> +      body: LoginBody()
Es al pedo extraer esto en un componente aparte si LoginScreen no va a tener nada más

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Signup/signup_screen.dart
> +      body: SignupBody()
Lo mismo, la abstracción está de más

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Welcome/components/WelcomeBody.dart
> +            */
Hay que eliminar esto

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Welcome/welcome_screen.dart
> +      body: WelcomeBody()
También, está al pedo esta abstracción

2020-11-03 21:07 UTC, w-etc commented on lib/components/already_have_an_account_acheck.dart
> +          onTap: press,
Ya que este check es específico de login/signup, les parece si la función press también la dejan en este archivo en vez de pasarla por parámetro?

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Login/components/LoginBody.dart
> +class LoginWidget extends State<LoginBody> {
La convención de Flutter es que este State se llame _LoginBodyState

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Login/components/background.dart
> +class Background extends StatelessWidget {
Estaría bueno especificar de qué es background este Background.

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Signup/components/SignupBody.dart
> +             */
Hay que borrar esto

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Signup/components/background.dart
> +class Background extends StatelessWidget {
Estaría bueno aclarar de qué es background este Background. Se va a usar en todas las pantallas o solo en autenticación?

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Signup/components/body.dart
> +}
Este componente no se usa en ningún lado

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Welcome/components/body.dart
> +class Body extends StatelessWidget {
Me tira que este componente no se usa en ningún lado

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Welcome/components/background.dart
> +class Background extends StatelessWidget {
Estaría bueno aclarar de qué es background este Background. Se va a usar en toda la página o solo en autenticación?

2020-11-03 21:07 UTC, w-etc commented on lib/screens/Signup/components/SignupBody.dart
> +              onChanged: (value) {},
Que onda esto?

2020-11-03 22:50 UTC, leodelgadodev commented
> Dejo cosas para corregir abajo, otras son preguntas
> 
> Una cosa que me pasó es que no encontré en la descripción del PR un instructivo para testearlo de forma local. Como me logueo? O no estaba incluido en el PR el comportamiento?

actualizada descripcion del PR para probarlo en local

2020-11-04 16:59 UTC, w-etc approved these changes
Faltan cambios por aplicar, pero a estas alturas prefiero no hacerlos bloqueantes

2020-11-04 18:09 UTC, merged