Funcionalidad votar marcadores
w-etc/geoStories pull request #20
Opened 2020-11-10 00:02 UTC by AntonellaDatri

### DESCRIPCIÓN
- los usuarios registrados pueden dar y sacar sus likes de un marcador 
- persistimos los likes de usuarios registrados
- los usuarios anónimos no pueden dar likes

2020-11-10 00:59 UTC, leodelgadodev requested changes

2020-11-10 00:59 UTC, leodelgadodev commented on lib/components/marker_icon.dart
> +
estos dos espacios en blanco despieran mis mas profundos TOCs

2020-11-10 00:59 UTC, leodelgadodev commented on lib/components/marker_icon.dart
> +
sacar esta linea en blanco

2020-11-10 00:59 UTC, leodelgadodev commented on lib/components/marker_icon.dart
> +
linea en blanco

2020-11-10 00:59 UTC, leodelgadodev commented on test/screens/like_marker_test.dart
> +  testWidgets('Usuario registrado like se persiste', (WidgetTester tester) async {
El nombre del test es medio confuso. Quedaria mejor ponerle algo tipo "Cuando un usuario que inicio sesion da like, se logra persistir en la base de datos"

2020-11-10 00:59 UTC, leodelgadodev commented on test/screens/like_marker_test.dart
> +
Espacios muchos vacios despues del });

2020-11-10 01:01 UTC, leodelgadodev commented
Entre con un usuario, di un like, cerre la app, entre como anonimo y podia darle likes (y hasta persistian los likes que di). De todas formas un merge reciente de Fede puede que arregle esto. Hay que probarlo a mano una vez que se mergee este PR

2020-11-10 12:37 UTC, ItuFede commented on test/screens/like_marker_test.dart
> +  testWidgets('Usuario registrado like se persiste', (WidgetTester tester) async {
Una forma de nomenclatura que se usa para test es [EstadoInicial]_[NombreDelSUT]_[EstadoEsperado]

2020-11-10 21:21 UTC, Nahue507 commented
> Entre con un usuario, di un like, cerre la app, entre como anonimo y podia darle likes (y hasta persistian los likes que di). De todas formas un merge reciente de Fede puede que arregle esto. Hay que probarlo a mano una vez que se mergee este PR

2020-11-11 00:25 UTC, leodelgadodev approved these changes

2020-11-11 02:41 UTC, merged